#!/bin/bash

set -euo pipefail
shopt -s extdebug

# generate AUTHORS, modify .mailmap in case of duplicates
# shellcheck disable=SC2016
git log --reverse --format='- %aN `<%aE>`' | perl -we '
BEGIN {
    %seen = (), @authors = ();
}
while (<>) {
    next if $seen{$_};
    $seen{$_} = push @authors, $_;
}
END {
    print "# Credits\n\n";
    print "All project contributors, ordered by first contribution.\n";
    print "\n", @authors, "\n";
    print "> Generated by `tools/authors.sh`\n";
}
' >"${BASH_SOURCE%/*}/../docs/AUTHORS.md"
