name: Codacy Coverage Workflow

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

permissions:
  contents: read

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: Codacy Coverage Reporter
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ''
